name: Invitation to join ML Fusion Lab
description: I would like to be part of this awesome community
title: "Please invite me to ML Fusion Lab"
labels: [welcome]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
